@startuml
left to right direction
actor "Utilisateur" as user
rectangle "Dashboard Rust/Egui" {
  usecase "S'identifier" as UC1
  usecase "Visualiser l'ensemble des ressources" as UC2
  usecase "Rechercher une ressource" as UC3
}
user --> UC1
user --> UC2
user --> UC3
@enduml
