@startuml
left to right direction
actor "Administrateur" as admin
rectangle "Dashboard Rust/Egui" {
  usecase "Authentification" as UC1
  usecase "Consulter le planning des tâches (Gantt)" as UC2
  usecase "Rechercher une tâche" as UC3
  usecase "Consulter les détails d'une tâche" as UC4
}
admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
@enduml
